#In this params.yaml file we r defining the parameter which was used in preparing the model
#for pretrained cnn model vgg-16
include_top: False
weights: 'imagenet'
input_shape: [224,224,3]
classes: 2
batch_size: 5
epochs: 10 #1 epochs= 1fp+1bp
learning_rate: 0.00001 #range lie btn 0 to 1 always kept as minimum as possible
augmentation: True