artifacts_root: artifacts

dataingestion:
  root_dir: artifacts/data_ingestion
  source_url: s3://raishmumbaibucket/Data.zip
  local_data_file: artifacts/data_ingestion
  unzip_dir: artifacts/data_ingestion