artifacts_root: artifacts

dataingestion:
  root_dir: artifacts/data_ingestion
  source_url: s3://raishmumbaibucket/Data.zip
  local_data_file: artifacts/data_ingestion
  unzip_dir: artifacts/data_ingestion


prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model.h5 #we download basemodel filepath to classify such vgg-16,resnet-model
  update_base_model_path: artifacts/prepare_base_model/base_model_update.h5
  