artifacts_root: artifacts

dataingestion:
  root_dir: artifacts/data_ingestion
  source_url: s3://raishmumbaibucket/Data.zip
  local_data_file: artifacts/data_ingestion
  unzip_dir: artifacts/data_ingestion


prepare_base_model:
  root_dir_path: artifacts/base_model
  base_model_path: artifacts/base_model/basemodel.h5
  update_base_model_path: artifacts/base_model/update_model.h5


prepare_callback_model:
  root_dir_path: artifacts/callback_model
  tensorboard_log_dir_path: artifacts/callback_model/tensorboard_log_dir_path
  model_checkpoint_path: artifacts/callback_model/model_checkpoint_path/model.h5 #after training best_model will save into this path in filename model.h5
  
